theme = "custom"
transparent_background = true

[custom_theme]
base = "catppuccin-mocha"
label = "Catppuccin Mocha (Custom)"
background = "#202023"
accent = "#cba6f7"
accentMuted = "#f5c2e7"
selectedHunk = "#cba6f7"
addedSignColor = "#a6e3a1"
removedSignColor = "#f38ba8"
badgeAdded = "#a6e3a1"
badgeRemoved = "#f38ba8"
badgeNeutral = "#b4befe"
fileNew = "#a6e3a1"
fileDeleted = "#eba0ac"
fileRenamed = "#74c7ec"
fileModified = "#89b4fa"
fileUntracked = "#fab387"
noteBorder = "#f5c2e7"
noteTitleText = "#f5e0dc"

[custom_theme.syntax]
default = "#f5e0dc"
keyword = "#cba6f7"
string = "#a6e3a1"
comment = "#b4befe"
number = "#fab387"
function = "#89b4fa"
property = "#89dceb"
type = "#f9e2af"
variable = "#f2cdcd"
operator = "#94e2d5"
punctuation = "#f5c2e7"
